name: chart_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dio: ^4.0.1
  elementary: ^2.0.0
  fl_chart: ^0.62.0
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.5
  dart_code_metrics: ^5.7.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  surf_lint_rules: ^2.1.0

flutter:
  uses-material-design: true
